### ISSUE TITLE
tickerMultiplex causes 100% CPU usage

### ISSUE THREAD

**Issue by faiface** [benjmarshall/gopixelsnake#1]
Hi! Cool game and thanks for using my lib ;)

However, your game consumer much more CPU than required and the reason is the `tickerMultiplex` function:

```go
func tickerMultiplex(out chan<- time.Time, tickerIn <-chan time.Time, startIn <-chan time.Time) {
	for true {
		select {
		case t := <-tickerIn:
			out <- t
		case t, ok := <-startIn:
			if !ok {
				return
			}
			out <- t
		default:
		}
	}
}
```

Due to the `default:` branch, this `for` loop spins furiously. Removing the default branch fixes the problem (the `select` will wait for either of the channels in such case, consuming no CPU).

**Comment by benjmarshall** [comment]
Thanks @faiface, good catch! I will issue an update shortly!

**Comment by benjmarshall** [comment]
Fixed in new release.
